# Starts control on :8080, worker on :8081, postgres database on :5433

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-U", "postgres", "-p", "5433"]
      interval: 5s
      timeout: 1s
      retries: 2

    command: -p 5433

    network_mode: host

  flyway:
    depends_on:
        db:
          condition: service_healthy

    image: flyway/flyway
    command: -url=jdbc:postgresql://localhost:5433/postgres -user=postgres -password=postgres migrate

    volumes:
      - ../src/icefarm/control/flyway/migrations:/flyway/sql

    network_mode: host

  worker:
    depends_on:
      flyway:
        condition: service_completed_successfully

    ports:
      - target: 8081
        published: 8081

    image: usbipiceproject/usbipice-worker:all
    build:
      context: .
      dockerfile: docker/dockerfile

    volumes:
      - /dev:/dev
      - /run/udev:/run/udev

    privileged: true

    # https://stackoverflow.com/questions/49687378/how-to-get-hosts-udev-events-from-a-docker-container
    # udev uses the AF_NETLINK socket to receive events from the kernel, which is why this fixes stuff
    # TODO get rid of this option
    network_mode: host
    user: root

    environment:
      USBIPICE_DATABASE: 'postgresql://postgres:postgres@localhost:5433/postgres'
      USBIPICE_VIRTUAL_IP: localhost
      USBIPICE_VIRTUAL_PORT: 8081
      USBIPICE_CONTROL_SERVER: http://localhost:8080
      USBIPICE_WORKER_NAME: host_worker
      USBIPICE_WORKER_LOGS: /usr/local/app/worker_logs
      USBIPICE_DEFAULT: src/icefarm/worker/firmware/default/build/default_firmware.uf2
      USBIPICE_PULSE_COUNT: src/icefarm/worker/firmware/pulse_count/build/bitstream_over_usb.uf2

    command: [".venv/bin/uvicorn", "icefarm.worker.app:run_uvicorn", "--env-file", ".uvicorn_env_bridge", "--port", "8081", "--factory", "--host", "0.0.0.0"]

  control:
    depends_on:
      flyway:
        condition: service_completed_successfully

    ports:
      - target: 8080
        published: 8080

    # only used for easy networking
    privileged: true
    network_mode: host

    image: usbipiceproject/usbipice-worker:all
    build:
      context: .
      dockerfile: deploy/dockerfile
    environment:
      USBIPICE_DATABASE: 'postgresql://postgres:postgres@localhost:5433/postgres'

    command: [".venv/bin/uvicorn", "icefarm.control.app:run_uvicorn", "--env-file", ".uvicorn_env_bridge", "--port", "8080", "--factory", "--host", "0.0.0.0"]
