name: upload

on:
  push:
    branches:
      - 'main'

env:
  IMAGE: evolvablehardware/icefarm:amd

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build amd
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: evolvablehardware/icefarm:amd
          file: docker/Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=evolvablehardware/icefarm:buildcache
          cache-to: type=registry,ref=evolvablehardware/icefarm:buildcache,mode=max

      - name: Compose Up
        run: docker compose -f docker/test_compose.yml up -d

      - name: Wait for compose
        run: sleep 2m

      - name: Run Tests
        run: docker compose -f docker/test_compose.yml exec client .venv/bin/pytest ./tests --url http://control:8080

      - name: Compose Logs
        run: docker compose -f docker/test_compose.yml logs

      - name: Compose Down
        run: docker compose -f docker/test_compose.yml down

      - name: Push amd
        run: docker push evolvablehardware/icefarm:amd

      - name: Build/Push arm
        uses: docker/build-push-action@v6
        with:
            push: true
            load: true
            tags: evolvablehardware/icefarm:arm
            file: docker/Dockerfile
            platforms: linux/arm64
            cache-from: type=registry,ref=evolvablehardware/icefarm:buildcache
            cache-to: type=registry,ref=evolvablehardware/icefarm:buildcache,mode=max

      - name: Create Multiarch
        run: docker buildx imagetools create -t evolvablehardware/icefarm:all evolvablehardware/icefarm:arm evolvablehardware/icefarm:amd