name: test

on:
  push:
    branches-ignore:
        - main
        - development

env:
  IMAGE: 'evolvablehardware/icefarm:amd'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build amd
        uses: docker/build-push-action@v6
        with:
          push: false
          load: true
          tags: evolvablehardware/icefarm:amd
          file: docker/Dockerfile
          platforms: linux/amd64
          cache-from: type=registry,ref=usbipiceproject/usbipice-worker:buildcache
          cache-to: type=registry,ref=evolvablehardware/icefarm:buildcache,mode=max

      - name: Compose Up
        run: docker compose -f docker/test_compose.yml up -d

      - name: Wait for compose
        run: sleep 2m

      - name: Run Tests
        run: docker compose -f docker/test_compose.yml exec client .venv/bin/pytest ./tests --url http://control:8080

      - name: Compose Logs
        run: docker compose -f docker/test_compose.yml logs

      - name: Compose Down
        run: docker compose -f docker/test_compose.yml down
